# Generated by Django 4.0.4 on 2022-05-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees_Task_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(auto_created='Not complete', max_length=100, verbose_name='status')),
                ('id_worker', models.IntegerField(max_length=1000, verbose_name='id_worker')),
                ('id_team', models.IntegerField(max_length=1000, verbose_name='id_team')),
                ('description', models.CharField(max_length=1000, verbose_name='description')),
                ('categories', models.CharField(max_length=1000, verbose_name='categories')),
                ('date_of_completion', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Employees_Task_List',
                'verbose_name_plural': 'Employees_Task_List',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TeamsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_admin', models.IntegerField(max_length=1000, verbose_name='id_admin')),
                ('name_team', models.CharField(max_length=1000, verbose_name='name_team')),
            ],
            options={
                'verbose_name': 'Teams',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_team', models.IntegerField(max_length=1000, verbose_name='id_team')),
                ('id_worker', models.IntegerField(max_length=1000, verbose_name='id_worker')),
            ],
            options={
                'verbose_name': 'Workers',
                'verbose_name_plural': 'Workers',
            },
        ),
    ]
